# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nxp/transport/agent.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'nxp/transport/agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19nxp/transport/agent.proto\x12\x03nxp\"I\n\x0e\x45xecuteRequest\x12\x10\n\x08skill_id\x18\x01 \x01(\t\x12\x13\n\x0bkwargs_json\x18\x02 \x01(\t\x12\x10\n\x08trace_id\x18\x03 \x01(\t\"5\n\x0f\x45xecuteResponse\x12\x13\n\x0bresult_json\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t2D\n\x0c\x41gentService\x12\x34\n\x07\x45xecute\x12\x13.nxp.ExecuteRequest\x1a\x14.nxp.ExecuteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nxp.transport.agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXECUTEREQUEST']._serialized_start=34
  _globals['_EXECUTEREQUEST']._serialized_end=107
  _globals['_EXECUTERESPONSE']._serialized_start=109
  _globals['_EXECUTERESPONSE']._serialized_end=162
  _globals['_AGENTSERVICE']._serialized_start=164
  _globals['_AGENTSERVICE']._serialized_end=232
# @@protoc_insertion_point(module_scope)
